sidecar:
  hostname: localhost
  health-uri: http://localhost:${sidecar.port}/app/health
spring:
  cloud:
    circuitbreaker:
      hystrix:
        enabled: false
  profiles:
#    active: zone-a,favorite-service-zone-a
    active: zone-b,favorite-service-zone-b
#    active: zone-a,video-service-zone-a
#    active: zone-b,video-service-zone-b

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    service-url:
      zoneA: http://127.0.0.1:8761/eureka
      zoneB: http://127.0.0.1:8762/eureka
    region: local-region
    availability-zones:
      local-region: zoneA,zoneB
    enabled: true

---
spring:
  profiles: zone-a
eureka:
  client:
    availability-zones:
      local-region: zoneA,zoneB
  instance:
    metadata-map:
      zone: zoneA

---
spring:
  profiles: zone-b
eureka:
  client:
    availability-zones:
      local-region: zoneB,zoneA
  instance:
    metadata-map:
      zone: zoneB

---
spring:
  profiles: favorite-service-zone-a
  application:
    name: favorite-service
server:
  port: 5678

sidecar:
  port: 9010

---
spring:
  profiles: favorite-service-zone-b
  application:
    name: favorite-service
server:
  port: 5679

sidecar:
  port: 9011

---
spring:
  profiles: video-service-zone-a
  application:
    name: video-service
server:
  port: 5688

sidecar:
  port:

---
spring:
  profiles: video-service-zone-b
  application:
    name: video-service
server:
  port: 5689

sidecar:
  port: 9021
